f+

diff --git a/.github/workflows/probe_servers_certs.yaml b/.github/workflows/probe_servers_certs.yaml
--- a/.github/workflows/probe_servers_certs.yaml
+++ b/.github/workflows/probe_servers_certs.yaml
@@ -34,10 +34,10 @@ jobs:
           #--------------#
           sudo apt update -y
           sudo apt install bc coreutils curl dos2unix fdupes jq moreutils wget -y
-          sudo apt-get install apt-transport-https apt-utils ca-certificates coreutils dos2unix gnupg2 jq moreutils p7zip-full rsync software-properties-common texinfo tmux util-linux wget -y 2>/dev/null ; sudo apt-get update -y 2>/dev/null
+          sudo apt-get install apt-transport-https apt-utils ca-certificates coreutils dos2unix gnupg2 jq moreutils postgresql postgresql-client p7zip-full rsync software-properties-common texinfo tmux util-linux wget -y 2>/dev/null ; sudo apt-get update -y 2>/dev/null
           # Do again, sometimes fails
           sudo apt install bc coreutils curl dos2unix fdupes jq moreutils wget -y
-          sudo apt-get install apt-transport-https apt-utils ca-certificates coreutils dos2unix gnupg2 jq moreutils p7zip-full rsync software-properties-common texinfo tmux util-linux wget -y 2>/dev/null ; sudo apt-get update -y 2>/dev/null
+          sudo apt-get install apt-transport-https apt-utils ca-certificates coreutils dos2unix gnupg2 jq moreutils postgresql postgresql-client p7zip-full rsync software-properties-common texinfo tmux util-linux wget -y 2>/dev/null ; sudo apt-get update -y 2>/dev/null
         continue-on-error: true
 
       - name: Set TZ to (Asia/Kathmandu)
@@ -114,27 +114,34 @@ jobs:
           # Presets
           set +x ; set +e
           #--------------#
-          # Download
-          curl -qfsSL "https://$INVENTORY_REPO_USER:$INVENTORY_REPO_TOKEN@raw.githubusercontent.com/Azathothas/Inventory/main/.github/scripts/probe_servers_certs.sh" -o "./probe_servers_certs.sh"
-          # Dos2unix
-          dos2unix --quiet "./probe_servers_certs.sh"
-          # chmod +xwr
-          sudo chmod +xwr "./probe_servers_certs.sh"
-          # Run
-          # Always run with STD_OUT + STD_IN >/dev/null
-          #bash "./probe_servers_certs.sh" >/dev/null 2>&1
-          #Debug
-          #bash "./probe_servers_certs.sh"
-          #Talscale + Tmux + gotty
-          curl -qfsSL "https://pub.ajam.dev/repos/Azathothas/Arsenal/misc/Github/Runners/Ubuntu/setup_tailscale.sh" -o "./setup_tailscale.sh" && dos2unix --quiet "./setup_tailscale.sh"
-          source "./setup_tailscale.sh"
-          tmux new-session -s "ivn" -d 'bash "./probe_servers_certs.sh" ; tmux kill-session -t "ivn" 2>/dev/null ; exit'
-          #nohup gotty --address "$TS_IP" --port "7070" --reconnect --reconnect-time 30 tmux attach-session -t "ivn" -r >/dev/null 2>&1 &
-          nohup gotty --address "127.0.0.1" --port "7070" --reconnect --reconnect-time 30 tmux attach-session -t "ivn" -r >/dev/null 2>&1 &
-          nohup gotty --address "127.0.0.1" --port "7777" --reconnect --reconnect-time 30 btop --tty_on >/dev/null 2>&1 &
-          echo -e "\n\n[+] Tmux TTY: http://$TS_DNS:7070"
-          echo -e "[+] BTOP: http://$TS_DNS:7777\n"
-          set +x ; while tmux has-session -t ivn ; do sleep 1 ; done
+          #Check
+          pg_isready --host="crt.sh" --port="5432" --username="guest" --dbname="certwatch" --timeout="10"
+          if [ $? -eq 1 ] || [ $? -eq 2 ] || [ $? -eq 3 ]; then
+              echo -e "\n[-] Failed to connect to crt.sh\n"
+              curl -qfsSL "https://crt.sh" -I
+          else
+             # Download
+             curl -qfsSL "https://$INVENTORY_REPO_USER:$INVENTORY_REPO_TOKEN@raw.githubusercontent.com/Azathothas/Inventory/main/.github/scripts/probe_servers_certs.sh" -o "./probe_servers_certs.sh"
+             # Dos2unix
+             dos2unix --quiet "./probe_servers_certs.sh"
+             # chmod +xwr
+             sudo chmod +xwr "./probe_servers_certs.sh"
+             # Run
+             # Always run with STD_OUT + STD_IN >/dev/null
+             #bash "./probe_servers_certs.sh" >/dev/null 2>&1
+             #Debug
+             #bash "./probe_servers_certs.sh"
+             #Talscale + Tmux + gotty
+             curl -qfsSL "https://pub.ajam.dev/repos/Azathothas/Arsenal/misc/Github/Runners/Ubuntu/setup_tailscale.sh" -o "./setup_tailscale.sh" && dos2unix --quiet "./setup_tailscale.sh"
+             source "./setup_tailscale.sh"
+             tmux new-session -s "ivn" -d 'bash "./probe_servers_certs.sh" ; tmux kill-session -t "ivn" 2>/dev/null ; exit'
+             #nohup gotty --address "$TS_IP" --port "7070" --reconnect --reconnect-time 30 tmux attach-session -t "ivn" -r >/dev/null 2>&1 &
+             nohup gotty --address "127.0.0.1" --port "7070" --reconnect --reconnect-time 30 tmux attach-session -t "ivn" -r >/dev/null 2>&1 &
+             nohup gotty --address "127.0.0.1" --port "7777" --reconnect --reconnect-time 30 btop --tty_on >/dev/null 2>&1 &
+             echo -e "\n\n[+] Tmux TTY: http://$TS_DNS:7070"
+             echo -e "[+] BTOP: http://$TS_DNS:7777\n"
+             set +x ; while tmux has-session -t ivn ; do sleep 1 ; done
+          fi
         continue-on-error: true
 
       - name: Upload Logs
